routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// HomeRoute
Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
//SocialLoginRoute
Route::get('login/{provider}', 'SocialController@redirectTo')->name('social');
Route::get('login/{provider}/callback', 'SocialController@handleCallback');
//OtherRoute
Route::view('about', 'aboutus.index')->name('about');
Route::view('contact', 'contact.index')->name('contact');
//ProductRoute
Route::resource('products', 'ProductController');
Route::get('products.category/{category?}', 'ProductController@productByCategory')->name('products.category');
Route::get('checkout', 'CheckoutController@index')->name('checkout');

Auth::routes();

//CartRoute
Route::resource('cart', 'CartController');
//UserInformationRoute
Route::resource('profile', 'ProfileController');
Route::get('profile.changePassword', 'ProfileController@changePassword')->name('profile.changePassword');
Route::put('profile.updatePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
Route::view('forgot-password', 'auth.reset')->name('forgot-password');
route::resource('paymentinfo', 'PaymentInfoController');

resources/views/layouts/master/carousel.blade.php
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="images/Spring Collection.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="images/Man.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="images/123.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

resources/views/layouts/master/footer.blade.php
<footer class="main-footer text-sm">
  <strong>Copyright &copy; 2020 <a href="#">BiTribie.info</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 0.0.2
  </div>
</footer>

resources/views/layouts/master/navbar.blade.php
<div class="site-navbar bg-white py-2">

  <div class="search-wrap">
    <div class="container">
      <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
      <form action="#" method="post">
        <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
      </form>
    </div>
  </div>

  <div class="container">
    <div class="d-flex align-items-center justify-content-between">
      <div class="logo">
        <div class="site-logo">
          <a href="{{route('home')}}" class="js-logo-clone">E-commerce</a>
        </div>
      </div>
      <div class="main-nav d-none d-lg-block">
        <nav class="site-navigation text-right text-md-center" role="navigation">
          <ul class="site-menu js-clone-nav d-none d-lg-block">
            <li class="{{ Request::segment(1) === 'home' ? 'active' : null }} {{ Request::segment(1) == '' ? 'active' : null }}"><a href="{{route('home')}}">Home</a></li>
            <li class="{{ Request::segment(1) === 'products' ? 'active' : null }} {{ Request::segment(1) === 'allproducts' ? 'active' : null }}"><a href="{{route('products.index')}}">All Product</a></li>
            <li class="{{ Request::segment(1) === 'contact' ? 'active' : null }}"><a href="{{route('contact')}}">Contact</a></li>
            <li class="{{ Request::segment(1) === 'about' ? 'active' : null }}"><a href="{{route('about')}}">AboutUs</a></li>
          </ul>
        </nav>
      </div>
      <div class="icons">
        <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
        <a href="{{ route('cart.index') }}" class="icons-btn d-inline-block bag">
          <span class="icon-shopping-bag"></span>
          {{-- <span class="number">2</span> --}}
        </a>
        @guest
        <a href="{{route('login')}}" class="icons-btn d-inline-block"><span class="icon-user-o"></span></a>
        @else
        <a class="icons-btn d-inline-block" data-toggle="dropdown"><span class="icon-user-o"></span></a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0 col-md-2">
          <div class="card card-widget widget-user mb-0 border-0">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header bg-info">
              {{-- <h3 class="widget-user-username">{{ Auth::user()->name }}</h3>
              <h5 class="widget-user-desc">Founder & CEO</h5> --}}
            </div>
            <div class="widget-user-image">
              @if(count(Auth::user()->images)>0)
              <img class="img-circle elevation-2" src="{{ asset(Auth::user()->images[0]->path) }}" style="width: 90px; height: 90px;"
                alt="User profile picture">
              @else
              <img class="img-circle elevation-2" src="../dist/img/user1-128x128.jpg"
                alt="User profile picture">
              @endif
            </div>
            <div class="card-footer">
              <div class="row justify-content-center align-self-center px-4 mb-3">
                <h3 class="widget-user-username">{{ Auth::user()->name }}</h3>
              </div>
              <div class="row">
                <div class="col-sm-6 border-right">
                  <div class="description-block">
                    <h5 class="description-header" onclick="location.href='{{ route('profile.index') }}'">Profile</h5>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                  <div class="description-block">
                    <h5 class="description-header"
                      onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</h5>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                      @csrf
                    </form>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
          </div>
        </div>
        {{-- <a href="{{route('logout')}}"onclick="event.preventDefault();document.getElementById('logout-form').submit();"
        class="icons-btn d-inline-block">
        <span class="icon-user-o"></span>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
          @csrf
        </form> --}}
        @endguest

      </div>

    </div>
  </div>
</div>