routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// HomeRoute
Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
//SocialLoginRoute
Route::get('login/{provider}', 'SocialController@redirectTo')->name('social');
Route::get('login/{provider}/callback', 'SocialController@handleCallback');
//OtherRoute
Route::view('about', 'aboutus.index')->name('about');
Route::view('contact', 'contact.index')->name('contact');
//ProductRoute
Route::resource('products', 'ProductController');
Route::get('products.category/{category?}', 'ProductController@productByCategory')->name('products.category');
Route::get('checkout', 'CheckoutController@index')->name('checkout');

Auth::routes();

//CartRoute
Route::resource('cart', 'CartController');
//UserInformationRoute
Route::resource('profile', 'ProfileController');
Route::get('profile.changePassword', 'ProfileController@changePassword')->name('profile.changePassword');
Route::put('profile.updatePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
Route::view('forgot-password', 'auth.reset')->name('forgot-password');
route::resource('paymentinfo', 'PaymentInfoController');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
    protected $fillable = ['product_code', 'product_code_type_id', 'name', 'description'];

    public function categories() {
        return $this->morphToMany('App\Models\Category', "categorizable");
    }

    public function productCodeType() {
        return $this->belongsTo('App\Models\ProductCodeType');
    }

    public function images() {
        return $this->morphToMany('App\Models\Image', "imageable");
    }

    public function productDetail(){
        return $this->hasMany('App\Models\ProductDetail');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\Cart;
use App\Models\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $products = Product::all();
        $defaultProductImagePath = "https://sciences.ucf.edu/psychology/wp-content/uploads/sites/63/2019/09/No-Image-Available.png";
        return view('product.product-list.index', compact('products', 'defaultProductImagePath'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */

    //Show Product Detail

    public function show(Product $product)
    {
        $defaultPath = "https://i2.wp.com/learn.onemonth.com/wp-content/uploads/2017/08/1-10.png?w=845&ssl=1";
        return view('product.detail.index', compact('product', 'defaultPath'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }

    public function productByCategory($category= NULL)
    {
        $defaultPath = "https://i2.wp.com/learn.onemonth.com/wp-content/uploads/2017/08/1-10.png?w=845&ssl=1";
        if ($category == 'men'){
            $products = Product::whereHas('categories', function($q){ $q->where('category_id', 1); })->paginate(12);
        }
        elseif ($category == 'women'){
            $products = Product::whereHas('categories', function($q){ $q->where('category_id', 2); })->paginate(12);
        }
        else{
            $products = Product::paginate(12);
        }
        return view('product.product-list.all-products-content', compact('products', 'defaultPath', 'category'));
    }
}

resources/views/product/product-list/all-products-content.blade.php
@extends('master')

@section('content')

<!--Main layout-->
<main>
    <div class="container">
        <!--Section: Block Content-->
        <section class="mt-5 mb-4">
            <!--Grid row-->
            <div class="row">
                <!--Left-->
                <div class="col-lg-3">
                    <div class="position-sticky">
                        <div class="border rounded p-4 single category mb-4">
                            <h3 class="side-title">Categories</h3>
                            <ul class="list-unstyled">
                                <li><a href="{{route('products.category', ['men'])}}" title="">Men <span
                                            class="float-right">13</span></a></li>
                                <li><a href="{{route('products.category', ['women'])}}" title="">Women <span
                                            class="float-right">13</span></a></li>
                                <li><a href="{{route('products.category', ['boys'])}}" title="">Boys <span
                                            class="float-right">13</span></a></li>
                                <li><a href="{{route('products.category', ['girls'])}}" title="">Girls <span
                                            class="float-right">13</span></a></li>
                                <li><a href="{{route('products.category', ['accessories'])}}" title="">Accessories <span
                                            class="float-right">13</span></a></li>
                            </ul>
                        </div>
                        <div class="border p-4 rounded">

                            {{-- Range Slider --}}
                            <div class="mb-4">
                                <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Price</h3>
                                <div id="slider-range" class="border-primary"></div>
                                <input type="text" name="text" id="amount"
                                    class="form-control border-0 pl-0 bg-transparent" disabled="" />
                            </div>

                            {{-- Size --}}
                            <div class="mb-4">
                                <h3 class="mb-3 h6 text-uppercase text-black d-block">Size</h3>
                                <label for="s_sm" class="d-flex">
                                    <input type="checkbox" id="s_sm" class="mr-2 mt-1"> <span
                                        class="text-black font-weight-normal">Small
                                        (2,319)</span>
                                </label>
                                <label for="s_md" class="d-flex">
                                    <input type="checkbox" id="s_md" class="mr-2 mt-1"> <span
                                        class="text-black font-weight-normal">Medium
                                        (1,282)</span>
                                </label>
                                <label for="s_lg" class="d-flex">
                                    <input type="checkbox" id="s_lg" class="mr-2 mt-1"> <span
                                        class="text-black font-weight-normal">Large
                                        (1,392)</span>
                                </label>
                            </div>

                            {{-- Colors --}}
                            <div class="mb-4">
                                <h3 class="mb-3 h6 text-uppercase text-black d-block">Color</h3>
                                <a href="#" class="d-flex color-item align-items-center">
                                    <span class="bg-danger color d-inline-block rounded-circle mr-2"></span> <span
                                        class="text-black">Red
                                        (2,429)</span>
                                </a>
                                <a href="#" class="d-flex color-item align-items-center">
                                    <span class="bg-success color d-inline-block rounded-circle mr-2"></span> <span
                                        class="text-black">Green
                                        (2,298)</span>
                                </a>
                                <a href="#" class="d-flex color-item align-items-center">
                                    <span class="bg-info color d-inline-block rounded-circle mr-2"></span> <span
                                        class="text-black">Blue
                                        (1,075)</span>
                                </a>
                                <a href="#" class="d-flex color-item align-items-center">
                                    <span class="bg-primary color d-inline-block rounded-circle mr-2"></span> <span
                                        class="text-black">Purple (1,075)</span>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
                <!--End Left-->

                <!--Right-->
                <div class="col-lg-9">
                    <!--Header-->
                    <div class="row align">
                        <div class="col-md-12 mb-3">
                            <div class="float-md-left d-flex">
                                <button class="btn btn-light"
                                    onclick="window.location='{{ route('products.index') }}'"><i
                                        class="fas fa-arrow-left"></i></button>
                                <h3 class="m-0 text-capitalize">{{$category ?? "All Products"}}</h3>
                            </div>
                            <div class="d-flex">
                                <div class="dropdown mr-1 ml-md-auto">
                                    <button type="button" class="btn btn-white btn-sm dropdown-toggle px-4"
                                        id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        Latest
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                                        <a class="dropdown-item" href="#">Men</a>
                                        <a class="dropdown-item" href="#">Women</a>
                                        <a class="dropdown-item" href="#">Boys</a>
                                        <a class="dropdown-item" href="#">Girls</a>
                                        <a class="dropdown-item" href="#">Accessories</a>
                                    </div>
                                </div>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-white btn-sm dropdown-toggle px-4"
                                        id="dropdownMenuReference" data-toggle="dropdown">Short By</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                                        <a class="dropdown-item" href="#">Relevance</a>
                                        <a class="dropdown-item" href="#">Name, A to Z</a>
                                        <a class="dropdown-item" href="#">Name, Z to A</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Price, low to high</a>
                                        <a class="dropdown-item" href="#">Price, high to low</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--End Header-->

                    {{-- List Products --}}
                    <div class="card-body">
                        <div class="container">
                            <div class="row mx-md-n3" id="ads">
                                <!-- Category Card -->
                                @foreach ($products as $product)
                                <div class="col-md-4">
                                    <div class="card rounded">
                                        <div class="card-image">
                                            <img class="img-fluid"
                                                src="{{asset($product->images[0]->path ?? $defaultPath)}}"
                                                alt="Alternate Text" />
                                        </div>
                                        <div class="card-body text-center">
                                            <div class="ad-title m-auto">
                                                <h5>{{$product->name}}</h5>
                                            </div>
                                            <a class="ad-btn" href="{{route('products.show', $product->id)}}">{{$product->productDetail()->min('price')}}</a>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                            <div class="row">
                                <div class="col-md-12 text-center mx-3">
                                    {{$products->links()}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End Right-->

                <!--Section: Block Content-->
            </div>
        </section>
    </div>
</main>
@endsection

resources/views/product/product-list/gallery-content.blade.php
<div class="content-wrapper col-md-8 mx-auto p-0">
    <div class="d-flex">
        @include('layouts.master.carousel')
    </div>

    <!-- Category -->
    <div class="site-section pb-0">
        <div class="container">

            <!-- Title -->
            <div class="title-section mb-5">
                <h2 class="text-uppercase"><span class="d-block">{{__('Discover')}}</span> {{__('The Collections')}}</h2>
            </div>

            <!-- items -->
            <div class="row align-items-stretch">
                <div class="main_categories col-lg-6 col-md-6 mb-4">
                    <div class="bg-white d-flex align-items-center"
                        style="height: 140px; background: url('https://i.ytimg.com/vi/2plos3DB2sI/maxresdefault.jpg'); background-size: contain; background-repeat: no-repeat;">
                        <h4 class="category_title w-50 mx-auto text-right" style="display: block;">MEN</h4>
                        <div class="sub_categories position-relative ml-auto mr-5" style="display: none">
                            <ul class="row list-unstyled m-0">
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['men'])}}">Shirts</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['men'])}}">Jean</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['men'])}}">Scarf</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="main_categories col-lg-6 col-md-6 mb-4">
                    <div class="bg-white d-flex align-items-center"
                        style="height: 140px; background: url('https://www.styleinmood.com/wp-content/uploads/2019/08/Most-Popular-Women-Fashion-Accessories-1.jpg'); background-size: contain; background-repeat: no-repeat;">
                        <h4 class="category_title w-50 mx-auto text-right" style="display: block;">WOMEN</h4>
                        <div class="sub_categories position-relative ml-auto mr-5" style="display: none">
                            <ul class="row list-unstyled m-0">
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['women'])}}">Shirts</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['women'])}}">Jean</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['women'])}}">Scarf</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="main_categories col-lg-6 col-md-6 mb-4">
                    <div class="bg-white d-flex align-items-center"
                        style="height: 140px; background: url('https://redtag-stores.com/en/wp-content/uploads/boys-fashion-denim-01-min.jpg'); background-size: contain; background-repeat: no-repeat;">
                        <h4 class="category_title w-50 mx-auto text-right" style="display: block;">BOY</h4>
                        <div class="sub_categories position-relative ml-auto mr-5" style="display: none">
                            <ul class="row list-unstyled m-0">
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['boys'])}}">Shirts</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['boys'])}}">Jean</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['boys'])}}">Scarf</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="main_categories col-lg-6 col-md-6 mb-4">
                    <div class="bg-white d-flex align-items-center"
                        style="height: 140px; background: url('https://i.ytimg.com/vi/I29t2q10UgM/maxresdefault.jpg'); background-size: contain; background-repeat: no-repeat;">
                        <h4 class="category_title w-50 mx-auto text-right" style="display: block;">GIRL</h4>
                        <div class="sub_categories position-relative ml-auto mr-5" style="display: none">
                            <ul class="row list-unstyled m-0">
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['girls'])}}">Shirts</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['girls'])}}">Jean</a></li>
                                <li class="sub_category p-2 px-3 font-weight-bold"><a href="{{route('products.category', ['girls'])}}">Scarf</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <div class=" site-section">
        <div class="container">

            {{-- Title --}}
            <div class="row">
                <div class="title-section mb-5 col-12">
                    <h2 class="text-uppercase">{{__('Products')}}</h2>
                </div>
            </div>

            {{-- Items --}}
            <div class="row">

                @for ($index=0; $index<4; $index++) <div class="col-lg-3 col-md-4 col-sm-2 item-entry mb-4">
                    <a href="{{route('products.show', $products[$index])}}" class="product-item sm-height bg-gray d-block">
                        <img class="img-fluid"
                            src="{{asset($products[$index]->images[0]->path ?? $defaultProductImagePath)}}" />
                    </a>
                    <h2 class="item-title"><a href="{{route('products.show', $products[$index])}}">{{ $products[$index]['name'] }}</a></h2>
                    <strong class="item-price">{{ $products[$index]->productDetail()->min('price') }}</strong>
                    <div class="star-rating">
                        <span class="icon-star2 text-warning"></span>
                        <span class="icon-star2 text-warning"></span>
                        <span class="icon-star2 text-warning"></span>
                        <span class="icon-star2 text-warning"></span>
                        <span class="icon-star2 text-warning"></span>
                    </div>
            </div>
            @endfor

        </div>

    </div>
</div>
</div>

@if (count($carts)>0)

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="title-section text-center mb-5 col-12">
                <h2 class="text-uppercase">{{__('Best Selling')}}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 block-3">
                <div class="nonloop-block-3 owl-carousel">
                    @for ($index=0; $index<5; $index++) <div class="item">
                        <div class="item-entry">
                            <a href="{{route('products.show', $carts[$index]->productDetail->product)}}" class="product-item md-height bg-gray d-block">
                                <img class="img-fluid"
                                    src="{{asset($carts[$index]->productDetail->images[0]->path ?? $defaultProductImagePath)}}" />
                            </a>
                            <h2 class="item-title"><a href="{{route('products.show', $carts[$index]->productDetail->product)}}">{{ $carts[$index]->productDetail->product->name }}</a>
                            </h2>
                            <strong class="item-price">{{ $carts[$index]->productDetail->price }}</strong>
                            <div class="star-rating">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                        </div>
                </div>
                @endfor

            </div>
        </div>
    </div>
</div>
</div>
@endif